baseURL = 'https://i1yakuk.github.io/hw_hugo/'
languageCode = 'ru-ru'
title = 'Ilya Site'
theme = 'PaperMod'

[params]
  author = 'Илья'
  description = 'Небольшой Сайт о себе и тем,чем занимаюсь'
  
[menu]
  [[menu.main]]
    name = 'Главная'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'О сайте'
    url = '/about/'
    weight = 2
  [[menu.main]]
    name = 'Блог'
    url = '/posts/'
    weight = 3
