baseURL = "https://i1yakuk.github.io/hw_hugo/"
languageCode = "ru-ru"
title = "???? ????"
theme = "PaperMod"

[languages]
  [languages.ru]
    weight = 1
    languageName = "???????"

[params]
  author = "????"
  description = "??? ???? ? ????????????????"

[[menu.main]]
  identifier = "home"
  name = "???????"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "blog"
  name = "????"
  url = "/posts/"
  weight = 2

[[menu.main]]
  identifier = "about"
  name = "??? ???"
  url = "/about/"
  weight = 3
