baseURL = "https://i1yakuk.github.io/hw_hugo/"
theme = "PaperMod"
title = "???? ???? ? ???-??????????"
languageCode = "ru-ru"

[params]
  author = "????"
  description = "??? ???? ? ???????????????? ? ???-??????????"
  defaultTheme = "auto"
